"""Shared taxonomies, seeds, config. Single source of truth (spec §7-8, §16, §19)."""
import random, os
import numpy as np

INTENTS = ["PRODUCT_INQUIRY","PRICE_INQUIRY","COVERAGE_INQUIRY","EXISTING_COVERAGE",
    "OBJECTION","COMPARISON","PURCHASE_INTEREST","FOLLOW_UP","REJECTION"]
EMOTIONS = ["POSITIVE","NEUTRAL","CONCERNED","SKEPTICAL","FRUSTRATED","ANGRY","ANXIOUS","SATISFIED"]
OBJECTIONS = ["NONE","PRICE_TOO_HIGH","ALREADY_INSURED","NO_NEED","DO_NOT_TRUST_INSURER",
    "NEED_MORE_INFORMATION","COMPARING_OPTIONS","BAD_PAST_EXPERIENCE","COVERAGE_NOT_CLEAR",
    "NEED_FAMILY_APPROVAL","NOT_READY"]
NEEDS = ["FAMILY_HEALTH","INDIVIDUAL_HEALTH","LIFE_PROTECTION","CHILD_PROTECTION","RETIREMENT",
    "INCOME_PROTECTION","CRITICAL_ILLNESS","ACCIDENT_PROTECTION","GENERAL_FINANCIAL_PROTECTION"]
PROFILES = ["PRICE_SENSITIVE","SKEPTICAL","FAMILY_ORIENTED","RISK_AVERSE","INFORMATION_SEEKING",
    "LOYAL_TO_EXISTING_INSURER","HESITANT","READY_TO_BUY"]
STAGES = ["GREETING","DISCOVERY","NEED_IDENTIFICATION","PRODUCT_EDUCATION","CONSIDERATION",
    "OBJECTION_HANDLING","EVALUATION","COMMITMENT","PURCHASE","FOLLOW_UP","REJECTION"]
# Spec §19 action space: PPO selects one of these actions.
ACTIONS = ["DISCOVER_NEEDS","ASK_CLARIFYING_QUESTION","DISCOVER_COVERAGE_GAP","EXPLAIN_PRODUCT",
    "VALUE_FRAMING","RISK_EXPLANATION","AFFORDABILITY_FRAMING","HANDLE_OBJECTION","YES_YES_FRAMING",
    "BUILD_TRUST","PERSONALIZE","COMPARE_OPTIONS","OFFER_ALTERNATIVE","ASK_FOR_COMMITMENT",
    "FOLLOW_UP","RESPECT_REJECTION"]

# Spec §8 controlled strategy taxonomy. PRODUCT_EDUCATION is an explicit v1.1 extension
# used by the EXPLAIN_PRODUCT action; required labels are otherwise unchanged.
STRATEGIES = ["NEED_DISCOVERY","CLARIFYING_QUESTION","COVERAGE_GAP_DISCOVERY","PRODUCT_EDUCATION",
    "VALUE_FRAMING","RISK_EXPLANATION","AFFORDABILITY_FRAMING","OBJECTION_HANDLING",
    "YES_YES_FRAMING","TRUST_BUILDING","PERSONALIZATION","FACTUAL_COMPARISON",
    "ALTERNATIVE_OFFER","COMMITMENT_REQUEST","FOLLOW_UP","RESPECT_REJECTION"]

ACTION_TO_STRATEGY = {
    "DISCOVER_NEEDS": "NEED_DISCOVERY",
    "ASK_CLARIFYING_QUESTION": "CLARIFYING_QUESTION",
    "DISCOVER_COVERAGE_GAP": "COVERAGE_GAP_DISCOVERY",
    "EXPLAIN_PRODUCT": "PRODUCT_EDUCATION",
    "VALUE_FRAMING": "VALUE_FRAMING",
    "RISK_EXPLANATION": "RISK_EXPLANATION",
    "AFFORDABILITY_FRAMING": "AFFORDABILITY_FRAMING",
    "HANDLE_OBJECTION": "OBJECTION_HANDLING",
    "YES_YES_FRAMING": "YES_YES_FRAMING",
    "BUILD_TRUST": "TRUST_BUILDING",
    "PERSONALIZE": "PERSONALIZATION",
    "COMPARE_OPTIONS": "FACTUAL_COMPARISON",
    "OFFER_ALTERNATIVE": "ALTERNATIVE_OFFER",
    "ASK_FOR_COMMITMENT": "COMMITMENT_REQUEST",
    "FOLLOW_UP": "FOLLOW_UP",
    "RESPECT_REJECTION": "RESPECT_REJECTION",
}

STRATEGY_TO_ACTION = {v: k for k, v in ACTION_TO_STRATEGY.items()}

def set_seed(seed=42):
    random.seed(seed); np.random.seed(seed)

def load_config(path="configs/base.yaml"):
    import yaml
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    for cand in [path, os.path.join(here, path)]:
        if os.path.exists(cand):
            with open(cand) as f:
                return yaml.safe_load(f)
    raise FileNotFoundError(path)

def onehot(idx, n):
    v = [0.0]*n; v[idx] = 1.0; return v
